### ISSUE TITLE
Admin panel for Content Service and Real-Time Toxic Text Detection

### ISSUE THREAD

**Issue by DmytroTeliukov** [UpTalent/ContentService#18]
### Description
The intent of the admin panel is to allow administrators to manage contents in the system effectively. The panel will provide admin with capabilities to alter the status of contents and notify them via author's email about the changes. The statuses could be Active, On Moderation, or Blocked.

### Tasks

- [x] Create ModerationStatus enum with the following statuses: ACTIVE, ON_MODERATION, BLOCKED
- [x] Add endpoint for blocking content with email notification
- [x] Add endpoint for unblocking content with email notification
- [x] Add endpoint to retrieve all contents with status ON_MODERATION and BLOCKED
- [x] Add endpoints to report content(set status to ON_MODERATION)
- [x] Configure PerspectiveApi client for toxic text detection
- [x] Send contents to moderation if their name or about me contains toxic text
- [ ] Connect with WebSocket. Whenever a content is transferred to the status ON_MODERATION, the server sends a message through this endpoint to the admin panel.
