### ISSUE TITLE
CRUD Operations for Content

### ISSUE THREAD

**Issue by MarkHmnv** [UpTalent/ContentService#2]
### Description
Talents can view, create, update, and delete proofs, while sponsors have the same privileges for vacancies. The aim is to extract and replicate essential functionality related to content management from the monolith app into the ContentService, allowing for a more modular and scalable architecture.

### Tasks
- [x] Talent and Sponsor can view proofs and vacancies
- [x] Talent can create proofs
- [x] Talent can update own proofs
- [x] Talents can delete own proofs
- [x] Sponsor can create vacancies
- [x] Sponsor can update own vacancies
- [x] Sponsor can delete own vacancies
