### ISSUE TITLE
Add skills, kudos, and all related logic

### ISSUE THREAD

**Issue by MarkHmnv** [UpTalent/ContentService#4]
### Description
Each proof provides evidence of the user's proficiency in a specific skill or area of knowledge. The system aims to empower users to demonstrate their capabilities to potential sponsors.

### Tasks
- [x] Create Skill schema and connect with Proof document
- [x] Add logic for kudossing proofs
- [ ] Connect Skill schema with Talent entity from AccountService
- [ ] Connect Skill schema with Vacancy document
